services:
  mongodb:
    image: mongo:7.0.0
    networks:
      - mongo-network
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pwd
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express:1.0.0
    networks:
      - mongo-network
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pwd
      - ME_CONFIG_BASICAUTH_USERNAME=ang
      - ME_CONFIG_BASICAUTH_PASSWORD=pwd
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL=mongodb://admin:pwd@127.0.0.1:27017
networks:
  mongo-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
volumes:
  mongo-data:
    driver: local

# docker run -d \
#   -p 27017:27017 \
#   -e MONGO_INITDB_ROOT_USERNAME=admin \
#   -e MONGO_INITDB_ROOT_PASSWORD=pwd \
#   --net mongo-network \
#   --name mongodb \
#   mongo

# docker run -d \
#   -p 8081:8081 \
#   -e ME_CONFIG_MONGODB_ADMINUSERNAME=admin \
#   -e ME_CONFIG_MONGODB_ADMINPASSWORD=pwd \
#   -e ME_CONFIG_BASICAUTH_USERNAME=ang \
#   -e ME_CONFIG_BASICAUTH_PASSWORD=pwd \
#   --net mongo-network \
#   --name mongo-express \
#   -e ME_CONFIG_MONGODB_SERVER=mongodb \
#   mongo-express
